{% set name = "python-monkey-business" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-monkey-business-{{ version }}.tar.gz
  sha256: 8393839cc741415ed5ddc2bd58e2d4ce07f966a7d26b7aebff19dcec64818edc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - ez_setup
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - six >=1.7.0

test:
  imports:
    - monkeybiz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/theatlantic/python-monkey-business
  license: BSD-2-Clause
  license_file: LICENSE
  summary: 'Utility functions for monkey-patching python code'
  license_family: BSD

extra:
  recipe-maintainers:
    - kwilcox
