{% set version = "1.0.0" %}
{% set sha256 = "2cb1820ff211e46f5a8a2f16c92c3e1d13ec528f3cf0c3afe1b6e895beb4e417" %}

package:
  name: python-monkey-business
  version: {{ version }}

source:
  fn: python-monkey-business-{{ version }}.tar.gz
  url: https://github.com/theatlantic/python-monkey-business/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - six >=1.7.0

  run:
    - python
    - setuptools
    - six >=1.7.0

test:
  imports:
    - monkeybiz

about:
  home: https://github.com/theatlantic/python-monkey-business
  license: BSD 2-Clause
  summary: 'Utility functions for monkey-patching python code'
  license_family: BSD

extra:
  recipe-maintainers:
    - kwilcox
