appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 0WZintAzsLhnE0VzhrYW8kBSCAbp/50iV2ix505EvcsLuwpqKGqMaBOvtf2VCKYeAiTOkvXGvUEIAV1cSaGOoXu4tQXDY4zV/h57/F1hefzD9pB7824ahXNs7rbCaurLm15ZjxtFjGSMB/SkMyBYdqMrDgilNIy6aBE+MFmGkf5QQ+l+GS0letI2/vTOn5dY2KJL0R66s+WJaohjrvsDDU1wugmVEmb2d9VziltD8S7A7pS6bAoPhYkH8F9o+bJemJpxhuwfH3Tg++Js+Keb/wlAlnVcJMn/5HvDFeYjV+3rh7BMb8llzflBJY5EgacR624u6InsfKVNBEGIIrAfACsC5M0m9h1DdJD1D1GWsJ7TSmvOe3f5GArTb5j3uULCPxSmC54aGbK4zFZnfPPoTnjp252ZWFE50zGtcKurLQVF2m81FEE+e5tMeY3eEzb8fFAm2QgthQX4EoT8mkMKQi4Hajj56o3A9GfrJZliW8U2GSjlb0C3IbZqVu+8nm34L7pu3alNmaGoHArT3GZOeh+/hq8hsM3gHHKLPwQaY1NJypdnLTWFyE5cdQXJzJHM7s4IoomxkNsT67ybV8KnMpCVMEYmWmzGaQaODccV9/SXWsr5zcsga8LAD2D7KIV/YhZMUopHWFQPWl6RC9xIIUxlM0MT2m9dFh3NIvC+XG8=}
